language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dmikusko/docker-react -f Dockerfile.dev .

script:
  - docker run dmikusko/docker-react npm run test -- --coverage